spring:
  application:
    name: delivery
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10

delivery:
  rates:
    base-cost: 5.0
    fragile: 0.2
    weight: 0.3
    volume: 0.2
    street: 0.2